albumsSuccess:
  metas:
    title:        Dharma Sangha - Photo Albums - eTapasvi.com

albumSuccess:
  metas:
    title:        Dharma Sangha - Photo Album - eTapasvi.com
    
#indexSuccess:
#  metas:
#    title:        Dharma Sangha - Photo - eTapasvi.com

showSuccess:
  metas:
    title:        Dharma Sangha - Photo - eTapasvi.com

contentSuccess:
  has_layout:     false