albumsSuccess:
  metas:
    title:        Photo Albums

albumSuccess:
  metas:
    title:        Photo Album
    
#indexSuccess:
#  metas:
#    title:        Dharma Sangha - Photo - eTapasvi.com

showSuccess:
  metas:
    title:        Photo
    
viewSuccess:
  metas:
    title:        Photo
    
contentSuccess:
  metas:
    title:        Photo
  has_layout:     false
  
albumcontentSuccess:
  metas:
    title:        Photo
  has_layout:     false