generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Audio
    theme:            default

    list:
      peer_method: doSelectWithI18n
      max_per_page: 1000
      sort: [order, desc]
      display: [id, show, order, =file, remote, title, author]
      filters: [show]
      object_actions:
        _edit:
        _delete:
        
    edit:
      display:
        "NONE": [created_at, show, file, remote, size, duration, order]
        "EN":       
          - title_i18n_en
          - body_i18n_en
          - author_i18n_en
        "RU":       
          - title_i18n_ru
          - body_i18n_ru
          - author_i18n_ru
        "CS":       
          - title_i18n_cs
          - body_i18n_cs
          - author_i18n_cs
        "HU":       
          - title_i18n_hu
          - body_i18n_hu
          - author_i18n_hu
        "PL":       
          - title_i18n_pl
          - body_i18n_pl
          - author_i18n_pl
        "FR":       
          - title_i18n_fr
          - body_i18n_fr
          - author_i18n_fr
        "zh_CN":       
          - title_i18n_zh_CN
          - body_i18n_zh_CN
          - author_i18n_zh_CN
        "vi":       
          - title_i18n_vi
          - body_i18n_vi
          - author_i18n_vi
        "de":       
          - title_i18n_de
          - body_i18n_de
          - author_i18n_de
        "it":
          - title_i18n_it
          - body_i18n_it
          - author_i18n_it
        "ja":
          - title_i18n_ja
          - body_i18n_ja
          - author_i18n_ja
        "es":
          - title_i18n_es
          - body_i18n_es
          - author_i18n_es
        "it":
          - title_i18n_it
          - body_i18n_it
          - author_i18n_it
        "et":
          - title_i18n_et
          - body_i18n_et
          - author_i18n_et
        "ne":
          - title_i18n_ne
          - body_i18n_ne
          - author_i18n_ne
        "bn":
          - title_i18n_bn
          - body_i18n_bn
          - author_i18n_bn
        "he":
          - title_i18n_he
          - body_i18n_he
          - author_i18n_he
        "zh_TW":
          - title_i18n_zh_TW
          - body_i18n_zh_TW
          - author_i18n_zh_TW

      fields:        
        title_i18n_en:
          name: Title
          params: disabled=false maxlength=255 style="width:80%"
        body_i18n_en:
          name: Body
          type: textarea_tag
          params: disabled=false size=118x6
        author_i18n_en:
          name: Author
          params: disabled=false maxlength=255 style="width:80%"
          
        title_i18n_ru:
          name: Title
          params: disabled=false maxlength=255 style="width:80%"
        body_i18n_ru:
          name: Body
          type: textarea_tag
          params: disabled=false size=118x6
        author_i18n_ru:
          name: Author
          params: disabled=false maxlength=255 style="width:80%"

        title_i18n_cs:
          name: Title
          params: disabled=false maxlength=255 style="width:80%"
        body_i18n_cs:
          name: Body
          type: textarea_tag
          params: disabled=false size=118x6
        author_i18n_cs:
          name: Author
          params: disabled=false maxlength=255 style="width:80%"
          
        title_i18n_hu:
          name: Title
          params: disabled=false maxlength=255 style="width:80%"
        body_i18n_hu:
          name: Body
          type: textarea_tag
          params: disabled=false size=118x6
        author_i18n_hu:
          name: Author
          params: disabled=false maxlength=255 style="width:80%"
          
        title_i18n_pl:
          name: Title
          params: disabled=false maxlength=255 style="width:80%"
        body_i18n_pl:
          name: Body
          type: textarea_tag
          params: disabled=false size=118x6
        author_i18n_pl:
          name: Author
          params: disabled=false maxlength=255 style="width:80%"
          
        title_i18n_fr:
          name: Title
          params: disabled=false maxlength=255 style="width:80%"
        body_i18n_fr:
          name: Body
          type: textarea_tag
          params: disabled=false size=118x6
        author_i18n_fr:
          name: Author
          params: disabled=false maxlength=255 style="width:80%"
          
        title_i18n_zh_cn:
          name: Title
          params: disabled=false maxlength=255 style="width:80%"
        body_i18n_zh_cn:
          name: Body
          type: textarea_tag
          params: disabled=false size=118x6
        author_i18n_zh_cn:
          name: Author
          params: disabled=false maxlength=255 style="width:80%"
          
        title_i18n_vi:
          name: Title
          params: disabled=false maxlength=255 style="width:80%"
        body_i18n_vi:
          name: Body
          type: textarea_tag
          params: disabled=false size=118x6
        author_i18n_vi:
          name: Author
          params: disabled=false maxlength=255 style="width:80%"
          
        title_i18n_de:
          name: Title
          params: disabled=false maxlength=255 style="width:80%"
        body_i18n_de:
          name: Body
          type: textarea_tag
          params: disabled=false size=118x6
        author_i18n_de:
          name: Author
          params: disabled=false maxlength=255 style="width:80%"
          
        title_i18n_it:
          name: Title
          params: disabled=false maxlength=255 style="width:80%"
        body_i18n_it:
          name: Body
          type: textarea_tag
          params: disabled=false size=118x6
        author_i18n_it:
          name: Author
          params: disabled=false maxlength=255 style="width:80%"

        title_i18n_ja:
          name: Title
          params: disabled=false maxlength=255 style="width:80%"
        body_i18n_ja:
          name: Body
          type: textarea_tag
          params: disabled=false size=118x6
        author_i18n_ja:
          name: Author
          params: disabled=false maxlength=255 style="width:80%"

        title_i18n_es:
          name: Title
          params: disabled=false maxlength=255 style="width:80%"
        body_i18n_es:
          name: Body
          type: textarea_tag
          params: disabled=false size=118x6
        author_i18n_es:
          name: Author
          params: disabled=false maxlength=255 style="width:80%"

        title_i18n_it:
          name: Title
          params: disabled=false maxlength=255 style="width:80%"
        body_i18n_it:
          name: Body
          type: textarea_tag
          params: disabled=false size=118x6
        author_i18n_it:
          name: Author
          params: disabled=false maxlength=255 style="width:80%"

        title_i18n_et:
          name: Title
          params: disabled=false maxlength=255 style="width:80%"
        body_i18n_et:
          name: Body
          type: textarea_tag
          params: disabled=false size=118x6
        author_i18n_et:
          name: Author
          params: disabled=false maxlength=255 style="width:80%"

        title_i18n_ne:
          name: Title
          params: disabled=false maxlength=255 style="width:80%"
        body_i18n_ne:
          name: Body
          type: textarea_tag
          params: disabled=false size=118x6
        author_i18n_ne:
          name: Author
          params: disabled=false maxlength=255 style="width:80%"

        title_i18n_bn:
          name: Title
          params: disabled=false maxlength=255 style="width:80%"
        body_i18n_bn:
          name: Body
          type: textarea_tag
          params: disabled=false size=118x6
        author_i18n_bn:
          name: Author
          params: disabled=false maxlength=255 style="width:80%"

        title_i18n_he:
          name: Title
          params: disabled=false maxlength=255 style="width:80%"
        body_i18n_he:
          name: Body
          type: textarea_tag
          params: disabled=false size=118x6
        author_i18n_he:
          name: Author
          params: disabled=false maxlength=255 style="width:80%"

        title_i18n_zh_tw:
          name: Title
          params: disabled=false maxlength=255 style="width:80%"
        body_i18n_zh_tw:
          name: Body
          type: textarea_tag
          params: disabled=false size=118x6
        author_i18n_zh_tw:
          name: Author
          params: disabled=false maxlength=255 style="width:80%"